package com.sentaca.redis.servertests;

public class TrafficGenerator {

  protected RandomGenerator random = new RandomGenerator();
  protected double tps;
  protected TestServer server;
  protected boolean stopRequested = false;

  /**
   * It hits the server with random traffic. It generates the constant traffic hits with
   * the desired TPS rate. The time between hits is generated by
   * "expotential distribution"
   * (http://en.wikipedia.org/wiki/Exponential_distribution).
   * 
   * @param tps
   * @param server
   */
  public TrafficGenerator(double tps, TestServer server) {
    this.tps = tps;
    this.server = server;
  }

  public void start() {
    Thread thread = new Thread(new Runnable() {

      @Override
      public void run() {
        try {
          while (!stopRequested) {
            long millis = (long) (1000 * random.expRandom(tps));
            Thread.sleep(millis);
            server.hit();
          }
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
      }
    });
    thread.start();
  }

  public void stop() {
    stopRequested = true;
  }
}
